spring.application.name=engine
# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/koncertify
spring.datasource.username=postgres
spring.datasource.password=pass123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Connection Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379